name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # اگر gradlew داخل ریپو نبود، به‌طور خودکار wrapper می‌سازیم
      - name: Ensure Gradle Wrapper exists
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found. Generating wrapper with Gradle 8.9..."
            # تلاش با gradle توزیع سیستم؛ اگر نبود، با اسکریپت موقتی
            set -e
            wget -q https://services.gradle.org/distributions/gradle-8.9-bin.zip -O /tmp/gradle-8.9-bin.zip
            unzip -q /tmp/gradle-8.9-bin.zip -d /tmp
            /tmp/gradle-8.9/bin/gradle wrapper --gradle-version 8.9
          fi
          chmod +x ./gradlew

      # یک لاگ کوتاه از محیط بیلد
      - name: Show project tree (top level)
        run: |
          ls -la
          test -d app && ls -la app || true

      # بیلد
      - name: Build Debug APK
        run: |
          ./gradlew --no-daemon --stacktrace clean :app:assembleDebug

      # نمایش خروجی‌ها برای عیب‌یابی
      - name: Show outputs under app/build/outputs
        run: |
          echo "----- listing app/build/outputs -----"
          ls -la app/build/outputs || true
          echo "----- listing apks recursively -----"
          find app/build/outputs -type f -name "*.apk" -print || true

      # آپلود همه‌ی APK ها (debug)
      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: |
            app/build/outputs/**/*.apk
          if-no-files-found: warn
