name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Clean project
        run: cd android && ./gradlew clean

      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug --stacktrace

      - name: Show APK path
        run: ls -R android/app/build/outputs/apk

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: VPN-App-Debug
          path: android/app/build/outputs/apk/debug/*.apk
