name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Gradle بدون نیاز به gradlew لوکال
      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.9"

      # اگر wrapper در ریپو نیست، روی رانر بسازش
      - name: Generate Gradle Wrapper (if missing)
        run: |
          if [ ! -f ./gradlew ]; then
            gradle wrapper --gradle-version 8.9
          fi
          chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Show APK path(s)
        run: |
          echo "----- listing */build/outputs -----"
          ls -R */build/outputs || true

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app/build/outputs/**/*.apk
          if-no-files-found: warn
          compression-level: 0
